### ISSUE TITLE
Oracle Doesn't Use "AS" for Aliases

### ISSUE THREAD

**Issue by recursivecodes** [micronaut-projects/micronaut-predator#13] opened 2019-07-20 02:29 UTC
When trying to run a simple `findById` with Predator, I receive the following exception:

```
22:21:38.621 [main] DEBUG io.micronaut.data.query - Executing Query: SELECT meal_.id,meal_,meal_.created_on,meal_.updated_on FROM meal AS meal_ WHERE (meal_.id = ?) FETCH NEXT 1 ROWS ONLY 
22:21:38.622 [main] TRACE io.micronaut.data.query - Binding parameter at position 1 to value 49ab813b-b588-4e35-bfdc-1c191b2e03e3
22:21:38.772 [main] ERROR i.m.h.server.netty.NettyHttpServer - Error starting Micronaut server: Error executing SQL Query: ORA-00933: SQL command not properly ended
```

The issue here is that Oracle doesn't support using "AS" for the table alias ([reference](https://stackoverflow.com/a/21145075/511250)). I'm figure the fix is to override [AS_CLAUSE](https://github.com/micronaut-projects/micronaut-predator/blob/0fe7480707c64a52dc0ba16ca9dcc9f5bed31c1e/predator-model/src/main/java/io/micronaut/data/model/query/builder/AbstractSqlLikeQueryBuilder.java#L30) if the Dialect is ORACLE, but I'm not sure where you want to do that.

**Comment by graemerocher** [comment] 2019-07-20 10:09
Thanks Todd, this is a regression because we had manually tested on Oracle earlier but lack regression tests. The reason being it doesn't seem possible to automate testing for Oracle via Travis CI due to the driver licensing issues. Is there a way around that? For MS SQL Server we could place a file in the source tree to agree to the license terms.

But yes It looks like we need to override the dialect for Oracle to handle this case.

**Comment by recursivecodes** [comment] 2019-07-20 13:16
Could you use the Oracle Maven repo to pull the drivers? It requires some setup, but I believe that once that setup is complete you are in compliance with the license agreements moving forward (but I'm no expert on licensing).  

https://blogs.oracle.com/dev2dev/get-oracle-jdbc-drivers-and-ucp-from-oracle-maven-repository-without-ides

If that doesn't work, let me know and I'll follow up internally to figure this out.

**Comment by graemerocher** [comment] 2019-07-22 08:39
@recursivecodes I have pushed a potential fix for this.

I got a little further with attempting some integration tests for Oracle on this branch:

https://github.com/micronaut-projects/micronaut-predator/commit/88deb32f1b5ceb2cd542a02062aebd31573d8e5b

However the next stumbling block is Oracle support for test containers (currently only OracleXE is supported?) and even then there are no public Docker images. I am not sure how or what the licensing restrictions are for publishing our own Docker images.

**Closed** 2019-07-22 14:30 UTC
Labels: bug

**Comment by gvenzl** [comment] 2019-07-22 16:40
The licensing and Docker images are currently in the works, but I can't say much more than that right now. Oracle XE allows redistribution, which means that one can build and use their own images. However, that is not true for SE2 and EE. That being said, Oracle 18c XE is compatible up to EE.
